name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
      CXXFLAGS: "/D_WIN32_WINNT=0x0A00"
    strategy:
      matrix:
        include:
          - qt_ver: 6.8.1
            qt_arch: win64_msvc2022_64
            msvc_arch: x64
            version: 2022
            qt_arch_install: msvc2022_64
            build_type: Debug

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          cmakeVersion: "~3.25.0"

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.83.0
          platform_version: 2022
          toolset: msvc
          link: static

      - name: Run vcpkg integrate install
        run: |
          vcpkg install libsodium
          vcpkg install libuv
          vcpkg install openssl
          vcpkg install pkgconf
          C:/vcpkg/vcpkg integrate install
        shell: cmd

      - name: Run CMake using CMakePresets.json and vcpkg toolchain
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'windows-debug'
          buildPreset: 'windows-debug'
          configurePresetAdditionalArgs: >
            [
              "-DBoost_NO_SYSTEM_PATHS=ON",
              "-DBoost_INCLUDE_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/include",
              "-DBoost_LIBRARY_DIRS=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib",
              "-DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake",
            ]
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          VCPKG_ROOT: C:/vcpkg
          PKG_CONFIG_PATH: C:/vcpkg/installed/x64-windows-static/lib/pkgconfig

      - name: Dep
        run: |
          dir
          dir .\build\debug
          dir .\build\debug\server
          dir .\build\debug\client
          dir .\build\debug\gui
          echo "---------------- ldd .\build\debug\server\server.exe"
          ldd .\build\debug\server\server.exe
          echo "---------------- ldd .\build\debug\client\client.exe"
          ldd .\build\debug\client\client.exe
          echo "---------------- ldd .\build\debug\gui\gclient.exe"
          ldd .\build\debug\gui\gclient.exe
          where.exe windeployqt
          echo "---------------- windeployqt .\build\debug\gui\gclient.exe"
          windeployqt .\build\debug\gui\gclient.exe --release --no-translations --no-system-d3d-compiler --no-compiler-runtime --dir .\build\debug\gui\
          dir .\build\debug\gui
          echo "---------------- cmake install"
          cmake --install build/debug
          echo "---------------- dir"
          dir
          echo "---------------- dir .\install\server"
          dir .\install\server
          echo "---------------- dir .\install\client"
          dir .\install\client
          echo "---------------- dir .\install\gclient"
          dir .\install\gclient
          echo "---------------- windeployqt .\build\debug\gui\gclient.exe"
          windeployqt .\build\debug\gui\gclient.exe --release --no-translations --no-system-d3d-compiler --no-compiler-runtime --dir .\install\gclient\
          echo "---------------- dir .\install\gclient"
          dir .\install\gclient
          echo "---------------- ldd .\install\gclient\gclient.exe"
          ldd .\install\gclient\gclient.exe
        shell: pwsh
