name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
      CXXFLAGS: "/D_WIN32_WINNT=0x0A00"
    strategy:
      matrix:
        include:
          - qt_ver: 6.8.1
            qt_arch: win64_msvc2022_64
            msvc_arch: x64
            version: 2022
            qt_arch_install: msvc2022_64
            build_type: Debug

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          cmakeVersion: "~3.25.0"

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.83.0
          platform_version: 2022
          toolset: msvc
          link: static

      - name: Run vcpkg integrate install
        run: |
          vcpkg install libsodium
          vcpkg install libuv
          vcpkg install openssl
          C:/vcpkg/vcpkg integrate install
        shell: cmd

      - name: Run CMake using CMakePresets.json and vcpkg toolchain
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'windows-debug'
          buildPreset: 'windows-debug'
          configurePresetAdditionalArgs: >
            [
              "-DBoost_NO_SYSTEM_PATHS=ON",
              "-DBoost_INCLUDE_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/include",
              "-DBoost_LIBRARY_DIRS=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib",
              "-DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake",
            ]
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          VCPKG_ROOT: C:/vcpkg
